exam/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
       path('tienda/', include('tienda.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tienda/urls.py
from django.urls import path

from . import views

app_name = "tienda"
urlpatterns = [
    path("", views.ProductoListView.as_view(), name="index"),
    path("<int:pk>/", views.ProductoDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", views.ProductoUpdateView.as_view(), name="update"),
    path("create/", views.ProductoCreateView.as_view(), name="create"),
    path("<int:pk>/delete/", views.ProductoDeleteView.as_view(), name="delete"),
    path("facturas", views.FacturaListView.as_view(), name="factura-index"),
    path("facturas/<int:pk>/", views.FacturaDetailView.as_view(), name="factura-detail"),
    path("facturas/<int:pk>/update/", views.FacturaUpdateView.as_view(), name="factura-update"),
    path("facturas/create/", views.FacturaCreateView.as_view(), name="factura-create"),
    path("facturas/<int:pk>/delete/", views.FacturaDeleteView.as_view(), name="factura-delete"),
    path("imagen/create/", views.ImagenCreateView.as_view(), name="imagen-create"),
    path("integrante/create/", views.IntegranteCreateView.as_view(), name="integrante-create"),
]

tienda/models.py
from django.db import models

# Create your models here.

class Integrante(models.Model):
    """Model definition for Integrante."""
    nombre= models.CharField(max_length=50)
    apellido= models.CharField(max_length=50)
    corrreo= models.CharField(max_length=50)

    class Meta:
        """Meta definition for Integrante."""

        verbose_name = 'Integrante'
        verbose_name_plural = 'Integrantes'

    def __str__(self):
        return self.nombre

    def get_absolute_url(self):
        return u'/tienda/create'
    

class Categoria(models.Model):
    """Model definition for Categoria."""
    #proyecto= models.ForeignKey(Proyecto,default=None,on_delete= models.PROTECT)
    nombre= models.CharField(max_length=50)
    
    class Meta:
        """Meta definition for Categoria."""

        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

    def __str__(self):
        return self.nombre
    
    def get_absolute_url(self):
        return u'/tienda/facturas/%d' % self.id 

class Image(models.Model):
    """Model definition for Image."""
    #proyecto= models.ForeignKey(Proyecto,default=None,on_delete= models.PROTECT)
    imagen= models.ImageField(upload_to="ropa",default=None,null=False)
    class Meta:
        """Meta definition for Image."""

        verbose_name = 'Image'
        verbose_name_plural = 'Images'

    def __str__(self):
        return str(self.imagen)
    
    def get_absolute_url(self):
        return u'/tienda/create'
    


class Proyecto(models.Model):
    """Model definition for proyecto."""
   
    nombre= models.CharField(max_length=50)
    descripcion= models.TextField(blank=True)
    fecha= models.DateField()
    imagen= models.ImageField(upload_to="ropa",null=False)
    categoria=models.ForeignKey(Categoria,default=None,on_delete= models.PROTECT)
    imagenes=models.ManyToManyField(Image)
    integrantes=models.ManyToManyField(Integrante)
    class Meta:
        """Meta definition for proyecto."""

        verbose_name = 'Proyecto'
        verbose_name_plural = 'Proyectos'

    def __str__(self):
        return self.nombre
    
    def get_absolute_url(self):
        return u'/tienda/%d' % self.id 

tienda/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views import generic
from .models import Proyecto, Categoria,Image,Integrante
from extra_views import CreateWithInlinesView, UpdateWithInlinesView, InlineFormSetFactory


class ProductoListView(generic.ListView):
    model = Proyecto
    template_name = "list.html"


class ProductoDetailView(generic.DetailView):
    model = Proyecto
    template_name = "detail.html"


class ProductoCreateView(generic.CreateView):
    model = Proyecto
    fields = '__all__'
    template_name = "form.html"


class ProductoUpdateView(generic.UpdateView):
    model = Proyecto
    fields = '__all__'
    template_name = "form.html"


class ProductoDeleteView(generic.DeleteView):
    model = Proyecto
    template_name = "delete.html"
    success_url = reverse_lazy('tienda:index')


class FacturaListView(generic.ListView):
    model = Categoria
    template_name = "facturas-list.html"


class FacturaDetailView(generic.DetailView):
    model = Categoria
    template_name = "facturas-detail.html"

    # def get_context_data(self, **kwargs):
    #   context = super(FacturaDetailView, self).get_context_data(**kwargs)
    #  context["detalle"] = Detalle.objects.filter(factura=self.object)
    # return context


# class DetalleInLine(InlineFormSetFactory):
 #   model = Detalle
  #  fields = '__all__'

class FacturaCreateView(CreateWithInlinesView):
    model = Categoria
    #inlines = [DetalleInLine]
    fields = '__all__'
    template_name = "facturas-form.html"


class FacturaUpdateView(UpdateWithInlinesView):
    model = Categoria
    #inlines = [DetalleInLine]
    fields = '__all__'
    template_name = "facturas-form.html"


class FacturaDeleteView(generic.DeleteView):
    model = Categoria
    template_name = "facturas-delete.html"
    success_url = reverse_lazy('tienda:factura-index')

class ImagenCreateView(generic.CreateView):
    model = Image
    fields = '__all__'
    template_name = "form-imagen.html"

class IntegranteCreateView(generic.CreateView):
    model = Integrante
    fields = '__all__'
    template_name = "form-integrante.html"

tienda/templates/base.html
{% load bootstrap4 %}
{% bootstrap_css %}

<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Menu</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"> </span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                <a class="nav-item nav-link active" href="/tienda">Proyectos<span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link active" href="/tienda/facturas">Categorias</a>
              </div>
            </div>
          </nav>
          <br><br>
{% block content %}
{% endblock %}
        
    </div>
    {% bootstrap_javascript jquery='full' %}
</body>

tienda/templates/delete.html
<form method="post">{% csrf_token %}
    <p>Seguro deseas eliminar "{{ object }}"?</p>
    <input type="submit" value="Confirmar">
</form>

tienda/templates/detail.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap4 %}
<a class="container padding-4 btn btn-primary" href="{% url 'tienda:update' proyecto.id %}">Actualizar</a>
<a class="container padding-4 btn btn-primary" href="{% url 'tienda:index' %}">Todos los proyectos</a>
<a class="container padding-4 btn btn-primary" href="{% url 'tienda:delete' proyecto.id %}">Eliminar</a>
<li class="list-group-item"><h1>{{ proyecto.nombre }}</h1>
   <br>  {{ proyecto.descripcion }}<br>{{ proyecto.fecha }}<br> {{ proyecto.categoria }}<br><img src="{{proyecto.imagen.url}}" style="max-height: 400px; max-width: 400px;">
   <h3>Integrantes:</h3>
   {% for integrantes in proyecto.integrantes.all %}
   {{integrantes.nombre}} {{integrantes.apellido}}<br>
   {% empty %}
       <li class="list-group-item">No hay integrantes.</li>
   {% endfor %}
</li>
<li class="list-group-item">
   {% for imagenes in proyecto.imagenes.all %}
    <img src="{{ imagenes.imagen.url }}" style="max-height: 200px; max-width: 200px;">
   {% empty %}
       <li class="list-group-item">No hay imagenes.</li>
   {% endfor %}
</li>
{% endblock %} 

tienda/templates/facturas-delete.html
<form method="post">{% csrf_token %}
        <p>Seguro deseas eliminar "{{ object }}"?</p>
        <input type="submit" value="Confirmar">
    </form>

tienda/templates/facturas-detail.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap4 %}
<a class="container padding-4 btn btn-primary" href="{% url 'tienda:factura-update' categoria.id %}">Actualizar</a>
<a class="container padding-4 btn btn-primary" href="{% url 'tienda:factura-index' %}">Todas las categorias</a>
<a class="container padding-4 btn btn-primary" href="{% url 'tienda:factura-delete' categoria.id %}">Eliminar</a>
<li class="list-group-item"><h1>{{ categoria.nombre }}</h1><h1>{{categoria.id}}</h1></li>

{% endblock %} 

tienda/templates/facturas-form.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap4 %}
<h1>Categoria</h1>
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    
    {% bootstrap_form form %}
    {% buttons %}
    <input class="btn btn-primary" type="submit" value="Enviar" />
    {% endbuttons %}
</form>
{% endblock %}

tienda/templates/facturas-list.html
    {% extends 'base.html' %}
    {% block content %}
    {% load bootstrap4 %}
    <a class="container padding-4 btn btn-primary" href="{% url 'tienda:factura-create' %}">Nuevo</a>
    <ul class="list-group">
        {% for categoria in object_list %}
             <li class="list-group-item"><a href="{% url 'tienda:factura-detail' categoria.id %}">{{categoria.nombre}}</a></li>
        {% empty %}
            <li>No hay productos.</li>
        {% endfor %}
  
    </ul>
    {% endblock %} 

tienda/templates/form-imagen.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap4 %}
<h1>Imagen</h1>
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    
    {% bootstrap_form form %}
    {% buttons %}
    <input class="btn btn-primary" type="submit" value="Enviar" />
    {% endbuttons %}
    </form>
{% endblock %}

tienda/templates/form-integrante.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap4 %}
<h1>Integrante</h1>
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    
    {% bootstrap_form form %}
    {% buttons %}
    <input class="btn btn-primary" type="submit" value="Enviar" />
    {% endbuttons %}
    </form>
{% endblock %}

tienda/templates/form.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap4 %}
<h1>Proyecto</h1>
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    
    {% bootstrap_form form %}
    {% buttons %}
    <input class="btn btn-primary" type="submit" value="Enviar" />
    {% endbuttons %}
</form>
{% endblock %}

tienda/templates/list.html
    {% extends 'base.html' %}
    {% block content %}
    {% load bootstrap4 %}
    <a class="container padding-4 btn btn-primary" href="{% url 'tienda:create' %}">Nuevo</a>
    <ul class="list-group">
        {% for proyecto in object_list %}
            <li class="list-group-item"><a href="{% url 'tienda:detail' proyecto.id %}">{{proyecto.nombre}}</a> - {{ proyecto.fecha }} <br><img src="{{proyecto.imagen.url}}" width="150" height="150"></li>
        {% empty %}
            <li>No hay productos.</li>
        {% endfor %}
  
    </ul>
    {% endblock %} 